version: "3"

services:
  db:
    image: postgres:13.2
    environment:
      POSTGRES_DB: singit
      POSTGRES_USER: singit
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8082:8080
